/*
 * NFT API Infura
 *
 * Query NFT data using Infura Nft Api 🚀
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetsModel struct {
	Contract string `json:"contract"`
	TokenId string `json:"tokenId"`
	Supply string `json:"supply"`
	Type_ string `json:"type"`
	Metadata *interface{} `json:"metadata,omitempty"`
}
