/*
 * NFT API Infura
 *
 * Query NFT data using Infura Nft Api 🚀
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CollectionModel struct {
	Contract string `json:"contract"`
	Name string `json:"name"`
	Symbol string `json:"symbol"`
	TokenType string `json:"tokenType"`
}
